version: '3'
services:
  aspnetcore:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'on-failure:10'
    ports:
      - '8080:80'
    depends_on:
      - db
    links:
      - db
  db:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deneme
      MYSQL_USERNAME: nekinci
      MYSQL_PASSWORD: nekinci
    volumes:
      - 'dbdata:/var/lib/mysql'
      - ./:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - '8090:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  dbdata:
