version: '3'
services:
  aspnetcore:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'on-failure:10'
    ports:
      - '8080:80'
    depends_on:
      - db
    links:
      - db
  db:
    image: 'mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - 'dbdata:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - '8090:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  dbdata:
