version: '3'
services:
  aspnetcore:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'on-failure:10'
    ports:
      - '8080:80'
    depends_on:
      - db
    links:
      - db
  db:
    image: 'mysql/mysql-server:5.6'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deneme
      MYSQL_USERNAME: nekinci
      MYSQL_PASSWORD: nekinci
      MYSQL_ROOT_HOST: '%'
    volumes:
      - 'dbdata:/var/lib/mysql'
      - ./:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - '8090:80'
    environment:
      MYSQL_USER: nekinci
      MYSQL_PASSWORD: nekinci
      MYSQL_ROOT_PASSWORD: root
volumes:
  dbdata:
