version: '3'

services: 
    aspnetcore:
        build: 
            context: .
            dockerfile: Dockerfile
        restart: on-failure:10
        ports: 
            - "8080:80"
        depends_on: 
            - db
    db:
        image: mysql/mysql-server:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: deneme
        volumes: 
            - dbdata:/var/lib/mysql 
volumes: 
    dbdata: 